version: '3'
services:
  app-countries:
    container_name: countries-quasar
    restart: always
    environment:
      - GIT_WORK_TREE=/usr/src/app
      - GIT_DIR=/usr/src/app/.git
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
