name: CI - Jest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - uses: expo/expo-github-action@v6
      with: 
        expo-version: 4.x
    - name: Build
      run: npm i
      
    - name: Test Coverage
      run: |
        SUMMARY="$(npm run test:coverage)
        TOKENS=($SUMMARY)
        echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
        
    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: bdf12e211619b048f9cbd75e89922b92
        filename: countries-vue_coverage.json
        label: Test Coverage
        message: ${{ env.COVERAGE }}
        color: green
        namedLogo: jest
