name: CI - Jest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - uses: expo/expo-github-action@v6
      with: 
        expo-version: 4.x
    - run: npm run test:coverage
