name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: node:18.11.0-alpine3.16

    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: make test
