name: CI - Jest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - uses: expo/expo-github-action@v6
      with: 
        expo-version: 4.x
    - name: Build
      run: npm i
      
    - name: Test Coverage
      run: npm run test:coverage
      
    - name: Monitor coverage
      uses: slavcodev/coverage-monitor-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coverage_path: "coverage/clover.xml"
        threshold_alert: 10
        threshold_warning: 50
        threshold_metric: "lines"
